# GitHub Actions workflow
# https://help.github.com/en/actions/reference
#
# Copyright Jeffrey Sharp
# SPDX-License-Identifier: ISC

name: Build
run-name: Build

on:
  push:
    branches:
      - main
      - next
      - release/*
    tags:
      - release/*
  pull_request:
    branches:
      - main
      - release/*
  workflow_dispatch:
    # no options

permissions:
  contents: write # required by ncipollo/release-action@v1

env:
  # Minimize noise from dotnet CLI
  DOTNET_NOLOGO: 1

jobs:
  build:
    name: Build
    runs-on: windows-latest
    #url: https://github.com/actions/virtual-environments

    steps:
      - name: Check Out Code
        uses: actions/checkout@v3
        #url: https://github.com/actions/checkout

      - name: Configure .NET 6.0
        uses: actions/setup-dotnet@v3
        #url: https://github.com/actions/setup-dotnet
        with:
          dotnet-version: |
            6.0.x
            8.0.x

      - name: Stamp Version
        id: stamp
        run: >
          dotnet build .root.targets -c Release
          -p:StampOnBuild=true
          -p:SetGitHubActionsVersion=true
          -p:Branch=${{ github.ref }}
          -p:Counter=${{ github.run_number }}
          -p:RepositoryCommit=${{ github.sha }}

      - name: Restore NuGet Packages
        run: dotnet restore

      - name: Build NuGet Packages
        run: >
          dotnet build --no-restore -c Release
          -p:TreatWarningsAsErrors=true
          -p:PackageOutputPath=${{ runner.temp }}\dist\

      - name: Build Service Package
        run: >
          dotnet publish RSMassTransit.Service --no-build -c Release
          -r win-x64
          -o ${{ runner.temp }}\bin\win-x64

      - name: Zip Service Package
        #url: https://sevenzip.osdn.jp/chm/cmdline/index.htm
        run: >
          7z a
          "${{ runner.temp }}\dist\RSMassTransit.Service-${{ steps.stamp.outputs.version }}-win-x64.zip"
          "${{ runner.temp }}\bin\win-x64\*"
          -r -mx=7

      - name: Test
        run: >
          dotnet test --no-build -c Release
          --settings Coverlet.runsettings
          --results-directory:${{ runner.temp }}\coverage\raw

      - name: Prepare Coverage Report
        uses: danielpalme/ReportGenerator-GitHub-Action@v5
        #url: https://github.com/danielpalme/ReportGenerator-GitHub-Action
        with:
          reports: ${{ runner.temp }}\coverage\raw\**\coverage.opencover.xml
          targetdir: ${{ runner.temp }}\coverage
          reporttypes: Html;MarkdownSummaryGithub;Badges
          verbosity: Warning

      - name: Save Coverage Report
        uses: actions/upload-artifact@v3
        #url: https://github.com/actions/upload-artifact
        with:
          name: Coverage Report
          path: ${{ runner.temp }}\coverage
          if-no-files-found: error

      - name: Publish Coverage Summary
        shell: pwsh
        run: >
          Get-Content $env:REPORT_PATH -Raw >> $env:GITHUB_STEP_SUMMARY
        env:
          REPORT_PATH: ${{ runner.temp }}\coverage\SummaryGithub.md

      - name: Save Packages
        uses: actions/upload-artifact@v3
        #url: https://github.com/actions/upload-artifact
        with:
          name: Packages
          path: ${{ runner.temp }}\dist
          if-no-files-found: error

      - name: Publish Client Packages
        if: startsWith(github.ref, 'refs/tags/release/')
        shell: pwsh
        run: >
          dotnet nuget push "${{ runner.temp }}\dist\RSMassTransit.Client.*.nupkg"
          -s https://api.nuget.org/v3/index.json
          -k $env:NUGET_API_KEY
          --skip-duplicate
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}

      - name: Publish Tool Package
        if: startsWith(github.ref, 'refs/tags/release/')
        shell: pwsh
        run: >
          dotnet nuget push "${{ runner.temp }}\dist\RSMassTransit.Tool.*.nupkg"
          -s https://api.nuget.org/v3/index.json
          -k $env:NUGET_API_KEY
          --skip-duplicate
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}

      - name: Publish PowerShell Module
        if: startsWith(github.ref, 'refs/tags/release/')
        shell: pwsh
        run: >
          dotnet nuget push "${{ runner.temp }}\dist\RSMassTransit.PowerShell.*.nupkg"
          -s https://www.powershellgallery.com/
          -k $env:PSGALLERY_API_KEY
          --skip-duplicate
          --no-symbols
        env:
          PSGALLERY_API_KEY: ${{ secrets.PSGALLERY_API_KEY }}

      - name: Create Release
        uses: ncipollo/release-action@v1
        #url: https://github.com/ncipollo/release-action
        if: startsWith(github.ref, 'refs/tags/release/')
        with:
          name: ${{ steps.stamp.outputs.version }}
          prerelease: ${{ contains('-', steps.stamp.outputs.version) }}
          draft: true
          bodyFile: CHANGES.md
          artifacts: ${{ runner.temp }}\dist\*
          artifactErrorsFailBuild: true
          token: ${{ secrets.GITHUB_TOKEN }}
